# Generated by Django 2.2.6 on 2019-11-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('keyword', models.CharField(default='', max_length=300)),
                ('des', models.CharField(default='', max_length=300)),
                ('favico', models.ImageField(null=True, upload_to='')),
                ('google', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cấu Hình SEO s',
            },
        ),
    ]
