# Generated by Django 2.2.6 on 2019-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cauhinhseo',
            options={'verbose_name_plural': 'Cấu Hình SEO'},
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='title',
            field=models.CharField(blank='Nhập tiêu đề website', default='', max_length=200),
        ),
    ]
