# Generated by Django 2.2.6 on 2019-11-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='fb_app',
            field=models.CharField(blank='', default='123456767890', max_length=100, verbose_name='Facebook app id'),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='robots',
            field=models.CharField(choices=[('noindex,nofollow', 'Chặn google lập chỉ mục trang web :(noindex,nofollow)'), ('index,follow', 'Lập chỉ mục trang web (index,follow)')], default='index,follow', help_text='Tùy chỉnh lập chỉ mục trang web với google', max_length=100, verbose_name='Robots'),
        ),
    ]
