# Generated by Django 2.2.6 on 2019-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0002_auto_20191107_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='title',
            field=models.CharField(default='Tiêu đề website', max_length=200),
        ),
    ]
