# Generated by Django 2.2.6 on 2019-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0003_auto_20191107_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='favico',
            field=models.ImageField(blank='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cauhinhseo',
            name='google',
            field=models.CharField(blank='', max_length=100, null=True),
        ),
    ]
