# Generated by Django 2.2.6 on 2019-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0005_auto_20191107_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhinhseo',
            name='google',
            field=models.CharField(blank='', default='', max_length=100, verbose_name='Google-Webmaster'),
        ),
    ]
