# Generated by Django 2.2.2 on 2019-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauHinh', '0011_auto_20191212_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhTrang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sim số đẹp - Thương hiệu sim số uy tín nhất việt nam', max_length=200, verbose_name='Tiêu đề website')),
                ('sdt1', models.CharField(default='0969641652', max_length=300, verbose_name='Số điện thoại 1')),
                ('sdt2', models.CharField(default='0969641652', max_length=300, verbose_name='Số điện thoại 2')),
                ('banner', models.ImageField(default='/favico.png', null=True, upload_to='', verbose_name='Banner đầu trang')),
                ('zalo', models.CharField(default='0969641652', max_length=300, verbose_name='Nhập số zalo')),
                ('chatfb', models.TextField(max_length=300, verbose_name='Nhập mã chat facebook')),
                ('footer', models.TextField(default='Nhập nội dung chân trang vào đây', max_length=1000, verbose_name='Thêm nội dung chân trang')),
            ],
            options={
                'verbose_name_plural': 'Cấu Hình Trang',
            },
        ),
    ]
