# Generated by Django 2.2.6 on 2019-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTGH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(default=1)),
                ('DonGia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TongTien', models.FloatField(default=0)),
                ('SanPhams', models.ManyToManyField(blank=True, to='sanpham.SanPham')),
            ],
        ),
    ]
