# Generated by Django 2.2.6 on 2019-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTGH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonGia', models.IntegerField(default=0, verbose_name='Giá')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TongTien', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('SanPhams', models.ManyToManyField(blank=True, to='sanpham.SanPham', verbose_name='Danh sách sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
    ]
