# Generated by Django 2.2 on 2019-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(default=1)),
                ('DonGia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayDatHang', models.DateTimeField(auto_now_add=True)),
                ('NgayGiaoHang', models.DateTimeField()),
                ('ThanhToan', models.BooleanField(default=False)),
                ('GiaoHang', models.BooleanField(default=False)),
            ],
        ),
    ]
