# Generated by Django 2.2 on 2019-05-15 16:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0002_auto_20190515_2201'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='giohang',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='ctgh',
            old_name='MaHD',
            new_name='GH',
        ),
        migrations.RenameField(
            model_name='ctgh',
            old_name='MaSP',
            new_name='SP',
        ),
        migrations.RenameField(
            model_name='giohang',
            old_name='MaKH',
            new_name='user',
        ),
    ]
