# Generated by Django 2.2.6 on 2019-12-02 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0002_auto_20191203_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt'),
        ),
    ]
