# Generated by Django 2.2 on 2019-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0003_auto_20190515_2333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='giohang',
            managers=[
            ],
        ),
    ]
