# Generated by Django 2.2.6 on 2019-11-27 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 32, 48, 291537, tzinfo=utc)),
        ),
    ]
