# Generated by Django 2.2.6 on 2019-11-27 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0002_auto_20191127_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 35, 16, 468721, tzinfo=utc)),
        ),
    ]
