# Generated by Django 2.2 on 2019-05-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giohang', '0005_auto_20190524_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayDatHang', models.DateTimeField(auto_now_add=True)),
                ('ThanhToan', models.BooleanField(default=False)),
                ('GiaoHang', models.BooleanField(default=False)),
                ('TongTien', models.FloatField(default=0)),
                ('GH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giohang.GioHang')),
            ],
        ),
    ]
