# Generated by Django 2.2.6 on 2019-11-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giohang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayDatHang', models.DateTimeField(auto_now_add=True)),
                ('ThanhToan', models.BooleanField(default=False)),
                ('GiaoHang', models.BooleanField(default=False)),
                ('TongTien', models.FloatField(default=0)),
                ('GH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giohang.GioHang')),
            ],
        ),
    ]
