# Generated by Django 2.2.6 on 2019-11-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoadon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoadon',
            options={'verbose_name_plural': 'Hóa đơn'},
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='GH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giohang.GioHang', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='GiaoHang',
            field=models.BooleanField(default=False, verbose_name='Giao hàng'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='NgayDatHang',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ThanhToan',
            field=models.BooleanField(default=False, verbose_name='Thanh toán'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='TongTien',
            field=models.FloatField(default=0, verbose_name='Tổng tiền'),
        ),
    ]
