# Generated by Django 2.2 on 2019-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Body', models.TextField()),
                ('CoverImage', models.ImageField(null=True, upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
