# Generated by Django 2.2.6 on 2020-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(null=True)),
                ('Short_Body', models.TextField(null=True)),
                ('Body', models.TextField()),
                ('CoverImage', models.ImageField(default='product-default.jpg', upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
