# Generated by Django 2.2 on 2019-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190620_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='CoverImage',
            field=models.ImageField(default='media/product-default.jpg', upload_to=''),
        ),
    ]
