# Generated by Django 2.2 on 2019-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190620_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='Short_Body',
            field=models.TextField(null=True),
        ),
    ]
