# Generated by Django 2.2 on 2019-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tintuc_short_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='Title',
            field=models.TextField(null=True),
        ),
    ]
