# Generated by Django 2.2.6 on 2019-11-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaMang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nhà mạng',
            },
        ),
        migrations.CreateModel(
            name='SimNamSinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sim năm sinh',
            },
        ),
        migrations.CreateModel(
            name='SimTheoGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sim theo giá',
            },
        ),
        migrations.CreateModel(
            name='SimTheoLoai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sim theo loại',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoSim', models.CharField(max_length=100)),
                ('Gia', models.IntegerField(default=0)),
                ('Anh', models.ImageField(null=True, upload_to='')),
                ('NgayNhap', models.DateTimeField(auto_now_add=True)),
                ('LoaiSims', models.ManyToManyField(blank=True, to='sanpham.SimTheoLoai')),
                ('Mang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.NhaMang')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm',
            },
        ),
    ]
