# Generated by Django 2.2.6 on 2019-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='TacVu',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'Sim Vip'), ('vipdn', 'Sim Vip Doanh Nhân')], default='thuong', max_length=100, verbose_name='Tác vụ trang chủ'),
        ),
    ]
