# Generated by Django 2.2.6 on 2019-11-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaisanpham',
            options={'verbose_name_plural': 'Loại sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='nhamang',
            options={'verbose_name_plural': 'Nhà mạng'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name_plural': 'Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='simnamsinh',
            options={'verbose_name_plural': 'Sim năm sinh'},
        ),
        migrations.AlterModelOptions(
            name='simtheogia',
            options={'verbose_name_plural': 'Sim theo giá'},
        ),
        migrations.AlterModelOptions(
            name='simtheoloai',
            options={'verbose_name_plural': 'Sim theo loại'},
        ),
    ]
