# Generated by Django 2.2.6 on 2019-11-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='Anh',
            field=models.ImageField(default='/default.png', upload_to='', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='NamSinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.SimNamSinh', verbose_name='Theo năm sinh '),
        ),
    ]
