# Generated by Django 2.2.6 on 2019-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='LoaiSims',
            field=models.ManyToManyField(blank=True, default=None, to='sanpham.SimTheoLoai'),
        ),
    ]
