# Generated by Django 2.2 on 2019-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='Anh',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
