# Generated by Django 2.2.6 on 2019-11-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20191102_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='TenSanPham',
            new_name='SoSim',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='GiamGia',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='MaLSP',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='MoTa',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='SoLuong',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='LoaiSims',
            field=models.ManyToManyField(blank=True, to='sanpham.SimTheoLoai'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Mang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.NhaMang'),
        ),
        migrations.DeleteModel(
            name='LoaiSanPham',
        ),
    ]
