# Generated by Django 2.2.6 on 2019-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0003_auto_20191102_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='TacVu',
            field=models.CharField(choices=[('thuong', 'Sim Thường'), ('khuyenmai', 'Sim Khuyến Mãi'), ('vip', 'Sim Vip'), ('vipdn', 'Sim Vip Doanh Nhân')], default='thuong', max_length=100),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='LoaiSims',
            field=models.ManyToManyField(blank=True, default=0, to='sanpham.SimTheoLoai'),
        ),
    ]
