# Generated by Django 2.2.6 on 2019-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20191107_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
    ]
