# Generated by Django 2.2.6 on 2019-11-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0005_sanpham_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhamang',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Anh',
            field=models.ImageField(null=True, upload_to='', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Gia',
            field=models.IntegerField(default=0, verbose_name='Nhập giá bán'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='LoaiSims',
            field=models.ManyToManyField(blank=True, default=0, to='sanpham.SimTheoLoai', verbose_name='Loại sim'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Mang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.NhaMang', verbose_name='Nhà Mạng'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='NgayNhap',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='SoSim',
            field=models.CharField(max_length=100, verbose_name='Nhập số sim'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='TacVu',
            field=models.CharField(choices=[('thuong', 'Sim Thường'), ('khuyenmai', 'Sim Khuyến Mãi'), ('vip', 'Sim Vip'), ('vipdn', 'Sim Vip Doanh Nhân')], default='thuong', max_length=100, verbose_name='Tác vụ trang chủ'),
        ),
        migrations.AlterField(
            model_name='simnamsinh',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='simtheogia',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='simtheoloai',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
    ]
