# Generated by Django 2.2.6 on 2019-11-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0006_auto_20191107_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='LoaiGia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.SimTheoGia', verbose_name='Sim theo giá '),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='NamSinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.SimNamSinh', verbose_name='Theo năm sinh '),
        ),
    ]
