# Generated by Django 2.2 on 2019-04-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='GioiTinh',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='NgaySinh',
        ),
    ]
