# Generated by Django 2.2.6 on 2019-11-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name_plural': 'Người dùng'},
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='MaLND',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='DiaChi',
            field=models.TextField(default='', verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='GioiTinh',
            field=models.CharField(choices=[('0', 'Nam'), ('1', 'Nữ'), ('2', 'Không xác định')], default='2', max_length=20, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='NgaySinh',
            field=models.DateField(null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='SDT',
            field=models.CharField(default='', max_length=10, verbose_name='Số điện thoại'),
        ),
        migrations.DeleteModel(
            name='LoaiNguoiDung',
        ),
    ]
