# Generated by Django 2.2 on 2019-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190427_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='GioiTinh',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
