# Generated by Django 2.2 on 2019-05-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customeruser_gioitinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiNguoiDung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoai', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customeruser',
            name='MaLND',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.LoaiNguoiDung'),
        ),
    ]
