# Generated by Django 2.2 on 2019-05-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190509_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='NgaySinh',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='MaLND',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.LoaiNguoiDung'),
        ),
    ]
