# Generated by Django 2.2 on 2019-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190509_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='NgaySinh',
            field=models.DateField(null=True),
        ),
    ]
