# Generated by Django 2.2 on 2019-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190509_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='XacThucEmail',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='XacThucSDT',
            field=models.BooleanField(default='False'),
        ),
    ]
