# Generated by Django 2.2 on 2019-06-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190513_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='XacThucEmail',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='XacThucSDT',
        ),
    ]
